//
// Created by wallnut on 5/11/16.
//

#ifndef JURISCHAT_2016_SERVER_CONSTANTS_H
#define JURISCHAT_2016_SERVER_CONSTANTS_H

const int MAX_ALLOWED_USERS = 16;
const int MAX_UNREAD_MESSAGES_STORED = 1024;

#endif //JURISCHAT_2016_SERVER_CONSTANTS_H
